---
title: "Projekt"
author: "Damian Kobyliński"
date: "2023-06-09"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Projekt

#install.packages("ggplot2")
#install.packages("dplyr")
#install.packages("fmsb")
#install.packages("RColorBrewer")
#install.packages("scales")


library(ggplot2)
library(dplyr)
library(fmsb)
library(RColorBrewer)
library(scales)

dataframe = read.csv("dataframe.csv", sep = ";")

# Podzial wystepowanie ze wzgledu na kontynent, rocznik, sex

# Ad.1

### Podzial na powszechne wystepowanie

prevelence = subset(dataframe, measure=="Prevalence")
only_number_of_prevelence = subset(prevelence, metric=="Number")
list_of_unique_area = unique(only_number_of_prevelence$location)

split_area =unique(split(only_number_of_prevelence,only_number_of_prevelence$location))

lapply(split_area,function(x){ title = toString(unique(x['location']))
ggplot(data = subset(x, location==x['location']), aes(x =
cause,y=as.double(val),fill=cause))+ geom_bar(stat = "identity",width =
0.4, position = position_dodge(width=2))+ theme(axis.text.x =
element_text(size = 4))+ ggtitle("Mental Disorders prevelence in `", title)+
xlab("Disorders")+ 
ylab("Occurrence")
})

# Ad. 2

### Pokaznie wedlug danych grup wiekowych

prevelence_by_age = split(only_number_of_prevelence,only_number_of_prevelence$age) 
prevelence_sum = lapply(prevelence_by_age, function(x)
       { aggregate(val ~ cause, data =x, FUN = sum) }
)

causesList = prevelence_sum$`10-14 years`$cause

# zsumowanie kategorii wiekowych 
category_sum_10_19 = data.frame(
  cause = causesList,
  val = prevelence_sum$`10-14 years`$val + prevelence_sum$`15-19 years`$val
)

category_sum_20_29 = data.frame(
  cause = causesList,
  val = prevelence_sum$`20-24 years`$val + prevelence_sum$`25-29 years`$val
)

category_sum_30_39 = data.frame(
  cause = causesList,
  val = prevelence_sum$`30-34 years`$val + prevelence_sum$`35-39 years`$val
)

category_sum_40_49 = data.frame(
  cause = causesList,
  val = prevelence_sum$`40-44 years`$val + prevelence_sum$`45-49 years`$val
)

# wrzucenie kategorii do jednej ramki danych
categories_grouped = data.frame(matrix(
    c(category_sum_10_19$val, category_sum_20_29$val, category_sum_30_39$val, category_sum_40_49$val),
    nrow = 4,
    byrow = T
  )
)
# zmiana nazw kolumn i wierszy
rownames(categories_grouped) = c("10 - 19", "20 - 29", "30 - 39", "40 - 49")
colnames(categories_grouped) = causesList

# sprawdzenie maksymalnej wartości w ramce
max(categories_grouped)

# dodanie zakresów
categories_grouped = rbind(600000000, 4000000, categories_grouped)

# wybor kolorów wykresu
coul <- brewer.pal(3, "Set2")
colors_border <- coul
colors_in <- alpha(coul, 0.3)

radarchart(categories_grouped,
    #custom polygon
    pcol=colors_border , pfcol=colors_in , plwd=3 , plty=1,
    #custom the grid
    cglcol="grey", cglty=1, axislabcol="black", cglwd=0.8, 
    #custom labels
    vlcex=0.8 
)
# legenda wykresu
legend(x=1, y=0.5, legend = rownames(categories_grouped[-c(1, 2), ]), bty = "n", pch=20 , col=colors_in , text.col = "grey", cex=1.2, pt.cex=3)
# Ad. 3 ### Przedstawienie progronz występowania danych chorób w następnych x latach 
prevelence_by_year = split(only_number_of_prevelence, only_number_of_prevelence$year)
prevelence_by_cause = lapply(prevelence_by_year, function(x) {split(x,x$cause)})

show_all_groups = lapply(prevelence_by_cause, function(x){ 
  for (i in 1:10){ 
    how_many_people = count(x[[i]],x[[i]]$age) 
    } 
})

prediction = lapply(prevelence_by_cause, function(x){ 
  for (i in 1:10){
    lm_model = lm(x[[i]]$val ~ x[[i]]$age, data=x[[i]]) 
    predicted_values = print(predict(lm_model, newdata = data.frame(age = x[[i]]$age))) 
    x[[i]] = cbind(x[[i]],predicted_values) 
    
    print(x[[i]])
  }
})

# Podzial na smierci ze wzgledu na kontynent, rocznik, sex

deaths = subset(dataframe, measure=="Deaths")
only_number_of_deaths = subset(deaths, metric=="Number")
list_of_unique_area_death = unique(only_number_of_deaths$location)

split_area_deaths =unique(split(only_number_of_deaths,only_number_of_deaths$location))


deaths_rows = list()
deaths_rows = append(deaths_rows,lapply(split_area_deaths,function(x){ list(x$cause, x$val)}))

lapply(split_area_deaths,function(x){ 
  title = toString(unique(x['location']))
  ggplot(data = subset(x, location==x['location']), aes(x = cause,y=as.double(val),fill=cause))+ 
  geom_bar(stat = "identity",width =0.4, position = position_dodge(width=2))+ 
  theme(axis.text.x = element_text(size = 4))+ 
  ggtitle("Mental Disorders deaths in ", title)+
  xlab("Disorders")+ 
  ylab("Occurrence") 
})

prevelence_by_age_deaths = split(only_number_of_deaths,only_number_of_deaths$age) 
prevelence_sum_deaths = lapply(prevelence_by_age_deaths, function(x)
       { aggregate(val ~ cause, data =x, FUN = sum) }
)

# Ad. 4 ### Przedstawienie liczby zachorowań w przedziale czasu
prevelence_by_year = split(only_number_of_prevelence, only_number_of_prevelence$year)
prevelence_by_year_sum = lapply(prevelence_by_year, function(x)
       { aggregate(val ~ cause, data = x, FUN = sum) }
)

# stworzenie list nazw lat
yearNameList = names(prevelence_by_year_sum)

# dodanie do każdej z ramek w prevelence_by_year roku
# Map() jest podobne do funkcji lapply(), ale różni się tym, że pobiera argumenty z wielu list i zwraca wynik w postaci listy wynikowej.
frames_with_year_list <- Map(cbind, prevelence_by_year_sum, year = yearNameList)

# dodanie ramek w jedną ramkę
# Funkcja do.call() pozwala na wywołanie funkcji, gdy argumenty funkcji są przechowywane w postaci listy lub wektora.
diseases_sum_by_year = do.call(rbind, frames_with_year_list)
head(diseases_sum_by_year)

# wykres
diseases_sum_by_year %>%
  ggplot(aes(x=year, y=val, group=cause, color=cause)) +
    geom_line() +
    ggtitle("Wykres ilości zachorowań na zaburzenia względem roku") +
    ylab("Ilość zachorowań") +
    # zamiana wartości w formacie naukowym na zwykły format
    scale_y_continuous(labels = comma)
    
# Ad. 5 ### Liczba zachorowań ze względu na płeć
prevelence_by_sex = split(only_number_of_prevelence, only_number_of_prevelence$sex)
prevelence_by_sex_sum = lapply(prevelence_by_sex, function(x)
       { aggregate(val ~ cause, data = x, FUN = sum) }
)

# lista nazw płci
genderNameList = names(prevelence_by_sex_sum)

# pętla po liście prevelence_by_sex generująca dwa wykresy zachorowań na zaburzenia względem płci
for (i in 1:length(prevelence_by_sex_sum)) {
  frame = prevelence_by_sex_sum[[i]]
  gender = ''
  if(genderNameList[i] == 'Female') gender = 'kobiet'
  else gender = 'mężczyzn'
  graph <- ggplot(frame, aes(x=cause, y=val, fill = cause)) + 
      geom_bar(stat = "identity") +
      coord_flip() +
      xlab("Zaburzenie") + 
      ylab("Ilość") +
      scale_y_continuous(labels = comma) +
      theme(legend.position = "none") +
      ggtitle(paste("Liczba zachorowań wśród", gender))
      
      
  print(graph)
}

```

